### ISSUE TITLE
comments about the tagging of the  documentation

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/tagpdf#15]
from @frastlin https://github.com/jgm/pandoc/issues/5409#issuecomment-480167907

I opened it and here are my comments:

1. when I opened it, the first message I got was: "Cannot extract the embedded font 'OZCXQN+LMSans10-Bold'. Some characters may not display or print correctly."
2. Acrobat does not ask me how to read the document, so first check passed.
3. Love the headings!
4. In the table of contents, the 1 doesn't have a link when all the other numbers do. I'm not sure why the numbers have the headings when the name of the heading is the name. Normally, in manuals, word table of contents, and Pandoc table of contents, the whole name of the heading is the link. When it is just the number, it's not always clear if the number is before or after the label, so I would much prefer the whole name be the link. I would also like the table of contents to be in a list. Here is what I see now:

```
1.
Introduction
link 2
1.1.
Tagging and accessibility...............................
link 3
1.2.
Engines and modes..................................
link 3
1.3.
References.......................................
```
(I added "Link" before the linked items). Here is what I would like:

```
List with 4 items
link 1. Introduction
link 1.1. Tagging and accessibility...............................
link 1.2. Engines and modes..................................
Link 1.3. References.......................................
```

Also note that links don't do anything when clicked.

5.  I'm not seeing links for references. I see the [1], but it's not a link.
6.  The list at 1.4. Validation, has the • on another line than the text, so it looks like:

```
•
One must check that the pdf is syntactically correct. It is rather easy to create broken pdf: e.g. if a chunk is opened on one page but closed on the next page.
```
Rather than:

`• One must check that the pdf is syntactically correct. It is rather easy to create broken pdf: e.g. if a chunk is opened on one page but closed on the next page.`

7. 2.2. Setup and activation has a list that has no bullets, dashes, or numbers to differentiate the list items, but I can tell it's a list with 15 items.
8. I like the alt text: "PAC3 report" which is the first graphic.

This is very good, and I would use it today if I could! I would like to test tables if you could give me a document with tables.

**Comment by u-fischer** [comment]
1. no idea yet
2. fine
3. fine
4. the table of contents has no links at all currently (I had to disable it as the structure of the link and the toc lines clashed). If you get a link it is probably due to some guessing of acrobat. But it is on my todo list to improve this.
5. Yes links in cites are an open point too (but shouldn't be too difficult, biblatex has good hooks). 
6. curious ;-). There is nothing special here imho. 
7. That's a description list. Every item starts with the name of an option. Can you see it? E.g. the first item should start with `activate-all`. I'm not sure if pdf/screenreaders know about this type of lists and how to handle it at best -- it is rather common in latex, so something sensible is needed.

**Comment by frastlin** [comment]
For number 6, this happens in HTML when a link is in a list. I'm sure there is some kind of styling thing that happens to separate the bullet from the list item.

I've never seen a list like in 7. maybe open an issue at [NVDA](https://github.com/nvaccess/nvda)
and report that this is a bug? If NVDA said "List item" before each item, that would help.

**Comment by u-fischer** [comment]
I'm closing this as the tagging of the documentation has changed a lot in the meantime. It would be nice to have some feed back about the tagging of the newest version 0.98a.
