### ISSUE TITLE
uncompress error

### ISSUE THREAD

**Issue by e-duckworth** [u-fischer/tagpdf#16]
Just updated everything to TeXLive 2019, tagpdf v0.60, etc.

I get an error on every example with the command "uncompress".  If I comment that line out everything works.

Hope this isn't too minor to bother reporting.

**Comment by u-fischer** [comment]
Thank you for the report. This will be resolved by an update this week. In the meantime the easiest is to use `\pdfvariable compresslevel 0 \pdfvariable objcompresslevel 0 `  instead (assuming lualatex).

**Comment by u-fischer** [comment]
a new version has been pushed to ctan and should be available tomorrow. Be aware that it needs the new versions of l3kernel and l3experimental which have been pushed today too.
