### ISSUE TITLE
not compile documents with latest version of L3 experemental

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [u-fischer/tagpdf#17]
When i try compile any document with your package and with updated l3 packages,i get an error:
Undefined control sequence.
\key code > uftag/setup/compresslevel/0 ...sable: 
                                                  
l.7
              uncompress,activate-all}
In attatchment you will see test document,in which you can check this issue and log file of this documents.
[test.zip](https://github.com/u-fischer/tagpdf/files/3347027/test.zip)

**Comment by u-fischer** [comment]
Thank you for the report. This will be resolved by an update this week. In the meantime the easiest is to use `\pdfvariable compresslevel 0 \pdfvariable objcompresslevel 0 `  and not the uncompress option (assuming lualatex).

**Comment by u-fischer** [comment]
a new version has been pushed to ctan and should be available tomorrow. Be aware that it needs the new versions of l3kernel and l3experimental which have been pushed today too.
