### ISSUE TITLE
Option tagunmakred=false results in invalid EMC operators 

### ISSUE THREAD

**Issue by bdoubrov** [u-fischer/tagpdf#23]
The attached document complied in Lua mode results in invalid EMC operators (no pairing BDC/BMC) at the beginning and at the end of the page contents

[issue_tagunmarked.txt](https://github.com/u-fischer/tagpdf/files/3735117/issue_tagunmarked.txt)

**Comment by u-fischer** [comment]
Hm, yes. There is an end misplaced in the lua. I made an hotfix branch "issue23" with a correction.
