### ISSUE TITLE
Feature request: possibility to create RoleMap in the output PDF

### ISSUE THREAD

**Issue by bdoubrov** [u-fischer/tagpdf#30]
One of the latest recommendations of PDF Association: 
https://www.pdfa.org/how-to-tag-titles-in-pdf-documents/ 
recommends using custom tag `<Title>` for document title with role mapping to `<P>`. It would be great have possibility implementing such recommendation in tagpdf.

**Comment by u-fischer** [comment]
This works already

~~~~
\documentclass{article}
\usepackage{tagpdf}
\tagpdfsetup{
  activate-all,
  add-new-tag=Title/P,
  uncompress,}
\pagestyle{empty}
\begin{document}
\tagstructbegin{tag=Document}
\tagstructbegin{tag=Title}
\tagmcbegin{tag=Title}
Title
\tagmcend
\tagstructend
\tagstructend
\end{document}
~~~~

gives a Title Structure Element, and a rolemap object with 

~~~~
3 0 obj
<</Title /P
>>
~~~~

~~~~
<< /Type /StructTreeRoot /K 4 0 R /ParentTree 2 0 R /RoleMap 3 0 R>>
~~~~

**Comment by bdoubrov** [comment]
Thanks a lot! I missed this in the documentation
