### ISSUE TITLE
not find global variable pdf_Core_active

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [u-fischer/tagpdf#32]
When i try to compile any document,using last commit of tagpdf package from branch splitting with lualatex,i get an error:

! Undefined control sequence.
<argument> \g__pdf_Core_active_bool

l.26 \bool_if:NF \g__pdf_Core_active_bool
For example i have this error in this document:

\documentclass{article}
\usepackage{tagpdf}
\tagpdfsetup{tabsorder=structure,uncompress,activate-all,add-new-tag=Title/P,interwordspace=true,tagunmarked=false}
\pagestyle{empty}
\begin{document}
\tagstructbegin{tag=Document}
\tagstructbegin{tag=Title}
\tagmcbegin{tag=Title}
Test
\tagmcend
\tagstructend
\tagstructend
\end{document}

**Comment by u-fischer** [comment]
This branch is work in progress. It requires the newest pdfresources code, it requires the newest latex-dev format, and it requires a special setup of the documents with commands where we haven't decided yet about the final names. 
Beside this it is (because of an error in the pdfresources code I just repaired locally) currently broken. 

Please don't use it for production.

**Comment by AlexandrKozlovskiy** [comment]
Ok,what branch i can use,for working with tagpdf package,except master branch,because i want to use the newest version of this package,but in branch master exists stable version of this package,but not newest.

**Comment by u-fischer** [comment]
The newest branch is this here. But as I said it is work in progress and need the accompaigning pdfresources branch and a latex format with the new hook management. It is not stable and I give no garanty that a commit represents a working state. I sometimes commit even if there is an error, only to save the work, and I also commit even if pdfresources and tagpdf did go out of sync.

**Comment by FrankMittelbach** [comment]
@AlexandrKozlovskiy my take is that you can't and should not use development branches for anything to "work with".
They are for our internal workflow not for  "usage".

In particular raising errors against them doesn't help anybody. We do have in some repositories (for example LaTeX2e) two more or less public branches "master" = stable version and "develop" = new but assumed to be correct version. All other branches are, as Ulrike said, work in progress and in all likelihood not suitable for "use" of any sort. They may even contain stuff that gets thrown away later or require special setups that others can't have,  etc.

So in repositories where we don't provide a "develop" branch the only branch for use is the stable version!

**Comment by AlexandrKozlovskiy** [comment]
> my take is that you can't and should not use development branches for anything to "work with".

imho,but all developers can use dev version of some product,if they want it. Yes,i understand,that dev version contains more bug,than stable,but i want to follow for the development of my very favourite product and have fixing of bugs,which exists in master branch,for example issue #25,which,as i understand,not fixed in branch master,and test all new features before appearing it in stable version. After testing it i can send bug report,to developers,to they fix all bugs before releasing of stable version or atl least know about this bugs.

> They are for our internal workflow not for "usage".

No,in my opinion,if it was committed in public repository,it can be used by anybody,but in this case,as you wrote,for work with this product it can require to apply some tricks. Before i used dev version of this package and in most cases haven't any errors. If you know,that in your commit exists some errors,please,announce about it in commit message or open a new issue with this error,as @u-fischer did before. So,in future i will use dev versions anyway.

**Comment by FrankMittelbach** [comment]
sorry, wrong choice of words. you can, of course, "use it"  in the sense of experience with it, but to use it in the sense of building upon it (and you said "to work with"), then there is a large likelihood that you see failures unless you use "master" or "develop" (if it exists) branch.
It would be quite a burden on shortlived branches to document depvendencies issues etc and therefore it is often not done which is why I said that such branches are not meant for public "use".

**Comment by u-fischer** [comment]
@AlexandrKozlovskiy  this is not a dev branch from a stable software project. It is an experimental branch for an experimental package. I created the branch to follow and test code from an experimental branch of another even more experimental and not released package in another repo. I keep the code public not for people to use it but so that I have backup and so that the code is not lost in case I can not longer work on it for some reason. 

I don't mind if you experiment with it, and if you comment I try to check this. But you are using it at your own risk, and I don't have neither the time nor the will to keep it constantly in a state fit for external use.  That said I updated the testfiles and they show how currently the code must be used (but it will perhaps change again).

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer Now it raise an error,that not find command \ProvidesExpl3Package. Ok,i added expl3 package,and now it raise an error Pdfresource~management~is~no~active!. I understoode,that you generate this error,using special latex command,so thank you very mutch,for drawing attention to this issue. @u-fischer,in what case i can send issues to you,because as i understoode,in this case i was shouldn't open this issue,because you knew,that previous (and probably also this) commit contains an errors. So,in ny opinion,renamedict is stable branch at this moment.

**Comment by u-fischer** [comment]
As I wrote: you need the newest latex-dev to run the code in this branch as it requires the new hook management we just implemented. That means your system must be up-to-date and you must use lualatex-dev or pdflatex-dev to compile. The log-file should say `LaTeX2e <2020-10-01> pre-release-7`.  

You also need the newest version of the splitting branch of pdfresources.

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer whether future release will be compatible with old versions of lualatex,for example with lualatex 2019,or future release will also works only with lualatex 2020 (i mean not only lualatex but,for example,pdflatex)? How i can update lualatex to this version,using miktex,or i should compile it,for example,via visual studio myself?

**Comment by u-fischer** [comment]
The tagging code will not work with older latex. tagpdf was written to identify what is missing in latex, and when we add such missing parts -- like now better hook support -- it will use it.  
But it should work with miktex, it has the newest latex-dev. Check in the miktex console if everything is installed and up-to-date.

**Comment by AlexandrKozlovskiy** [comment]
I updated lualatex and tryed to delete code,which check,whether pdf_Core_active exists,but i hadn't any structure in structure tree. If it possible,please,can you fix this,because in newest version of this package exists some fixes e.g fixes in lua mode. Yes,i did it for master branch for myself,modifying tagpdf.lua and now all works ok for me,but it exist people,who haven't knowledges of lua and understanding,how it works.

**Comment by u-fischer** [comment]
@AlexandrKozlovskiy  Sorry I have no idea what you did and which problem you have. 

If you have an issue that I can reproduce with the current development  code (both of tagpdf and pdfresources) I will try to correct it. For this I need a small example. 

But I will not adapt or correct older versions of the code or problems with locally changed files. If you modified tagpdf.lua you are on your own.

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer Ok,when i compile any document in lualatex even with latest version of pdfresources and tagpdf (both from splitting branch),i get an error:

! Package tagpdf Error: Pdfresource management is no active!
(tagpdf)                tagpdf will no work..

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer How now fix this issue,because now it seems,what i have all necessary for using of new version of tagpdf.

**Comment by u-fischer** [comment]
You could read the whole error message:

    Type  H <return>  for immediate help.

If you do this it tells you

```
Activate it with
\RequirePackage{pdfresources}
\DeclareDocumentMetaData{<options>}
before loading the class
```

But be aware that we are just discussing internally the interfaces and that it can change shortly.
