### ISSUE TITLE
Not clickable links in examples and in documentation to tagpdf package

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [u-fischer/tagpdf#35]
When i open pdfs with example of tagging of contents and with documentation of tagpdf,all links not clickabl (at least with nvda). Yes,screenreader see all links as links,but during pressing enter cursor not move to place,which was referenced by this link,so nothing happens. In other things in your documentation to tagpdf all ok in accessibility.

**Comment by u-fischer** [comment]
with which version of the documentation did you try? The one from ctan or from the splitting branch?

**Comment by AlexandrKozlovskiy** [comment]
from ctan.

**Comment by AlexandrKozlovskiy** [comment]
I looked at the pdf examples of tagging of sections,and for tableofcontants is the same issue,as for documentation and the same examples from ctan.

**Comment by AlexandrKozlovskiy** [comment]
I remember,what in one of the examples sighted human test it,and links not works to. So,it's probably not accessibility issue.

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer Why you closed this issue? In your tagpdf.pdf file links still not clickable. But in pdf document,connected with tagpdf sources,links are clickable,but this document it seems is not tagged.

**Comment by AlexandrKozlovskiy** [comment]
This issue exists in main and develop branches in adobe reader.

**Comment by u-fischer** [comment]
> Why you closed this issue?

Because it is too vage and it is unclear if it is still valid.

if you see an problem then open an new issue and give an exact file name and a clear description which link doesn't work.

**Comment by AlexandrKozlovskiy** [comment]
For example file source/tagpdf.pdf in nain and develop branch. After clicking on link we should go on the section,which connected with this link,but instead of this we have nothing. and this is in each tagged pdf document in your package. See an example on https://www.pdfa.org/wp-content/uploads/2019/06/TaggedPDFBestPracticeGuideSyntax.pdf,and in this example links of the contents are clickable and reference on section,connected with this link.

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer Have you any questions to me,or you understood reason of this issue?

**Comment by u-fischer** [comment]
I checked in https://ngpdf.com. It didn't recognize the links in tagpdf either, but Boris confirmed me that this is a bug in ngpdf not in tagpdf. I suspect that nvda has the same problem and suggest that you make a bug report there.

(tagpdf doesn't used structure destinations yet, as this requires probably changes in the engines, but only "normal" page destinations, but this is also the case in the best practice guide so not the cause of the problem.)

**Comment by u-fischer** [comment]
No I won't reopen it. I can click on links and they work and the code looks right. So until I get a clear counterproof  I will assume that the bug is in nvda or in the adobe api they use.  So make a bug report for nvda.

**Comment by AlexandrKozlovskiy** [comment]
@U-fischer But why in example,about which i wrote before,all ok?
