### ISSUE TITLE
Only one mc kid inserted in table in lua mode

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [u-fischer/tagpdf#36]
May be i do something wrong,but when i try to do autotagging of table,i have only one mc tag inside table,despite according to the log,in structure tree saved more then one kid. Also according to the log only one mc inserts. In generic mode all ok. In attachment you will see tex+pdf+log files which i get in lualatex and in pdflatex. The issue happens in master and in splitting branch of tagpdf package. Examples was compiled using splitting branch and lualatex/pdflatex which was released at first october 2020 year. I simplified document as it possible,so i not used command with optional arguments. If i use command for starting of the line with optional argument,the error is not disappeared. Thank you very much for fixing of this issue and for any help.
[tabular.zip](https://github.com/u-fischer/tagpdf/files/5518125/tabular.zip)

**Comment by u-fischer** [comment]
sorry I don't time now to look really, but at first glance I would say that you didn't take into account that attributes are set locally and that tabular cells build groups.

**Comment by AlexandrKozlovskiy** [comment]
Ok,when you will have a time,please,look at this and in issue #35 . May be i can do something myself to avoid this issue inside our package,in which i do tagging of tables,and if yes,how i can do it,and i will try modify code of our package myself? Because i did,in my opinion,very good tagging of tabular inside our package,which use your package and which we develop,with THead and with TBody,so this tables read very good by nvda,and it's very pitty,that tagging of tables not works correct in lua mode. If i can not do anymore,i will wait fixing of this issue. As i wrote,i simplified my document,as it possible,to you can see an issue.

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer When i reopen td after original & and open/close tr,td etc out of \noalign,all works ok,but in this case,as i understand,i will have an errors in multicolumn tables. So,as i understand,there is no way to solve it in lua mode,or i wrong? If yes,why? @u-fischer,can you in future create generic+lua mode? In this mode all will works as in generic mode,but closing/opening mc between pages will be using nodes via lua,as it works now in lua mode.

**Comment by u-fischer** [comment]
attributes are global again now, so this probably no longer relevant.
