### ISSUE TITLE
RMarkdown \TagP not working

### ISSUE THREAD

**Issue by dianalost** [u-fischer/tagpdf#38]
https://github.com/u-fischer/tagpdf/blob/70371fa9c4e8a1921c7f6d45276c325ca7a038f2/source/tagpdf.tex#L115

Hi,

I'm working on tagging a pdf with the use of Rmarkdown. I'm using tagpdf.tex in the source as a guide for it, and I'm having trouble with the \TagP and \TagP^ part. 

! Undefined control sequence.
l.134   \TagP
              your text

**Comment by u-fischer** [comment]
\TagP was defined in a special patch file I use for the documentation, but in the newest version I no longer use it, paragraphs are tagged differently (with the help of new hooks in latex-dev) and I removed the command. 

Be aware that tagpdf is a package for experiments not production. It can always change at short notice.

**Comment by dianalost** [comment]
Oh ok that explains it, thanks for the fast response!
