### ISSUE TITLE
Opensuse, tagpdf and l3pdf

### ISSUE THREAD

**Issue by JST55** [u-fischer/tagpdf#39]
I was using tagpdf to partially tag materials I am writing for my students in latex on opensuse using pdflatex.  After the latest update of texlive my code will not run.  The error says tagpdf requires l3pdf but it cannot find l3pdf.  A little research showed me that l3pdf is now in the kernel.  How do I tell tagdpf not to look for that package?

Thank you for any help.

**Comment by u-fischer** [comment]
A current tagpdf doesn't require l3pdf. I adapted it to the changes in the kernel and it works fine here. 

In case you are using an older version and want to update: be aware that it will require the new pdfmanagement-testphase code and so changes to the document.
