### ISSUE TITLE
AFInline

### ISSUE THREAD

**Issue by maiettada** [u-fischer/tagpdf#42]
Hello @u-fischer , hello everybody

I paste the images to explain what I see.
I am using the example ex-AF-file.pdf downloaded from the ctan page.
But what I see is empty alternate texts ("Testo alternativo" in the images).

By reading the  example ex-AF-file.tex file, I should find the following alternate texts:
- Bär with teh shir
- Duck
- Additional info!
Can you please check? 
Note: I'm using Adobe Acrobat Pro 2017

![immagine](https://user-images.githubusercontent.com/78794373/121381955-77383c80-c946-11eb-8092-c2d20c5e0302.png)

![immagine](https://user-images.githubusercontent.com/78794373/121381881-6687c680-c946-11eb-8c21-c61e1364a71a.png)

![immagine](https://user-images.githubusercontent.com/78794373/121380891-8cf93200-c945-11eb-8401-07276b64e228.png)

**Comment by u-fischer** [comment]
The example is not about alternate text but about associated files, that is a new feature of PDF 2.0. The embedded files are in the PDF, you can check, the PDF is uncompressed, but I have no idea if and how adobe  shows such embedded files. 

You can try http://ngpdf.com/. If you upload the file there you will see the attachments

![image](https://user-images.githubusercontent.com/4047173/121387013-9f299f00-c94a-11eb-9452-0334c37906c9.png)

But I should have set the version to pdf 2.0 in this example, I will correct that in the next version.
