### ISSUE TITLE
code breaks with luatex 1.09

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/tagpdf#5]
With luatex 1.09 the mc-step breaks with 

~~~~
tagpdf: INSERT BDC 0...ents/Git/tagpgf/source/texmf/tex/latex/tagpdf/tagpdf.lua:
142: creating a whatsit requires the subtype number as a second argument
stack traceback:
	[C]: in function 'node.new'
	...ents/Git/tagpgf/source/texmf/tex/latex/tagpdf/tagpdf.lua:142: in upvalue '__
uftag_insert_bdc_node'
~~~~

This must be checked  and corrected ...

**Comment by u-fischer** [comment]
could be a bug in the engine, see https://mailman.ntg.nl/pipermail/dev-luatex/2018-August/006075.html

**Comment by zauguin** [comment]
The bug is fixed in the current LuaTeX SVN trunk.

**Comment by u-fischer** [comment]
@zauguin  Thanks! I just checked with the w32tex binaries and the error is gone.
