### ISSUE TITLE
Tagpdf

### ISSUE THREAD

**Issue by LatexNewbie** [u-fischer/tagpdf#50]
So i am having an issue when compiling my latex with lualatex, it states there is an undefined control sequence in line 91 of the axessibility.sty. Line 91 is shown in the screenshot below. Do you know what the issue is?

![image](https://user-images.githubusercontent.com/99299581/153097307-e4dcce15-e590-44f6-bb7f-25c40e4af4bf.png)

**Comment by u-fischer** [comment]
I removed the commands in the newest version. The axessibility package authors will have to update its code and use the recommended iftex package instead for the test. They should also correct the content, they shouldn't set a catalog value with the primitive command, that is incompatible with the pdf management: they create a duplicated key in the catalog. And loading glyphtounicode is unneeded in a current latex, that is already in the format.

Open an issue here https://github.com/integr-abile/axessibility/issues

As a work around to avoid the error (but this doesn't resolve all issues!) you can add this before loading the package:

~~~~
\ExplSyntaxOn
\cs_set_eq:NN\tagpdfifluatexTF \sys_if_engine_luatex:TF
\cs_set_eq:NN\tagpdfifluatexT  \sys_if_engine_luatex:T
\cs_set_eq:NN\tagpdfifpdftexT  \sys_if_engine_pdftex:T
\ExplSyntaxOff
~~~~

Be aware that tagpdf is an experimental package, it is mainly a tool to research tagging. Take the warnings at the begin of its documentation seriously!
