### ISSUE TITLE
Adjust orders of structure elements

### ISSUE THREAD

**Issue by lvjr** [u-fischer/tagpdf#64]
In PDF, mark contents and structure elements are independent. But it seems `tagpdf` has not yet provided a way for adjusting positions of structure elements.

This issue is from https://github.com/lvjr/tabularray/issues/88. In building a long table, `tabularray` typesets `TBody` before `THead`, therefore the orders of these two structure elements need to be exchanged in PDF.

Also in PDF and HTML, `Caption` must be the first element of `Table`, but in LaTeX users can put captions at the end of `table` environments. Therefore it is important to provide some interface for adjusting positions of structure elements.

**Comment by u-fischer** [comment]
See the keys `stash`,  `label`, `parent`  key and the `\tagstructuse` command. Together they allow you switch the order of structure elements in various ways. (For the mc there are similar options.)

**Comment by lvjr** [comment]
Thank you. And maybe the documentation needs more examples.

**Comment by car222222** [comment]
All documentation always needs more examples, and more explanations, and more . . . :-)
