### ISSUE TITLE
\tag_stop:, \tag_start:, \tag_stop:n and \tag_start:n

### ISSUE THREAD

**Issue by lvjr** [u-fischer/tagpdf#65]
In the documentation file `tagpdf.pdf`, there is no description of commands `\tag_stop:`, `\tag_start:`, `\tag_stop:n` and `\tag_start:n`. And only three of them are mentioned in the change log.

Also in `tagpdf-base.sty`, two `#1`s are missing in the definitions of these commands.
```latex
%<*base>
\cs_new_protected:Npn \tag_stop:{}
\cs_new_protected:Npn \tag_start:{}
\cs_new_protected:Npn \tag_stop:n{}
\cs_new_protected:Npn \tag_start:n{}
%</base>
```

**Comment by u-fischer** [comment]
thanks, corrected.
