### ISSUE TITLE
Missing spaces with lualatex

### ISSUE THREAD

**Issue by krypt-n** [u-fischer/tagpdf#66]
[From tex.stackexchange](https://tex.stackexchange.com/questions/674471/missing-space-with-pdfmanagement-and-lualatex)

In some cases when using tagpdf together with lualatex, some spaces are missing. A small example:

```latex
\DocumentMetadata{
    testphase=phase-I
}

\documentclass{article}

\begin{document}

$\{a\} \mbox{test}$
$\{a\} \mbox{ test}$
$\{a\}\ \mbox{test}$

\end{document}
```

Output with lualatex:
<img width="139" alt="Screenshot 2023-02-08 at 17 03 54" src="https://user-images.githubusercontent.com/1621822/217626478-eb5698fb-6e8d-44fa-a3e4-e89fb8ebf496.png">
(no space after the second pair of braces)

Output with pdflatex or without `\DocumentMetadata`:
<img width="139" alt="Screenshot 2023-02-08 at 17 07 03" src="https://user-images.githubusercontent.com/1621822/217626534-119d43ae-264d-47f7-b13d-5cfa606877d8.png">
(a space after the second pair of braces, which I think is the expected behavior)

Edit: A smaller example that exhibits what I think is the same behavior:
```
\DocumentMetadata{
    testphase=phase-I
}

\documentclass{article}

\begin{document}

a \mbox{b} a \mbox{ b} a \mbox{b}

\end{document}
```

**Comment by car222222** [comment]
I can confirm that this ouput shows the  “correct” spaces. 

> Output with pdflatex or without \DocumentMetadata:

**Comment by krypt-n** [comment]
Using version 0.98d, it now works as I would expect. Thanks!
