### ISSUE TITLE
Use two colors with paratagging-show option

### ISSUE THREAD

**Issue by lvjr** [u-fischer/tagpdf#69]
After turning on `paratagging-show` option, when I do something wrong with tagging, I get the following result:
![parcolor1](https://user-images.githubusercontent.com/4239949/218231127-6b39170d-36b5-427d-9023-c0fb51f0124d.png)

The colors at both `para/begin` and `para/end` positions are the same. And it is quite hard to discover the tagging problem. When using two different colors by some hack, I will get the following better result:
![parcolor2](https://user-images.githubusercontent.com/4239949/218231253-525cb854-5a71-411c-aa2b-59762cf41939.png)

**Comment by u-fischer** [comment]
yes, we noticed that already, and in other code use two colors (and even prefixes), I will move that to tagpdf to have there two colors too.

**Comment by u-fischer** [comment]
The new version uses two colors.

**Comment by lvjr** [comment]
Green on white hurts users' eyes. Its wcag color contrast is 1.37:1, too far away from minimal requirement 3:1 or 4.5:1. For a project focusing on user accessibility, I don't think it is a good choice even in debug display.

**Comment by car222222** [comment]
A very good point!

**Comment by u-fischer** [comment]
yes I know that red/green isn't the best. But blue as used in your example doesn't work well for me (not enough contrast to the black text).  At some time there will be some option to change the content, but only after we merged in the list code (which uses an extended definition). As the code is currently in a public hook, you can adjust it if you want.

**Comment by lvjr** [comment]
> yes I know that red/green isn't the best. But blue as used in your example doesn't work well for me (not enough contrast to the black text).

I assume in most of the time the background is white. I could help to find proper colors if only white and black backgrounds are considered. For contents with any background you have to put paragraph numbers into colorboxes. I think it is no harm to use colorboxes for debug output. 

>As the code is currently in a public hook, you can adjust it if you want.

......
