### ISSUE TITLE
Paratagging causes extra blank line after display math

### ISSUE THREAD

**Issue by wangweixuan** [u-fischer/tagpdf#86]
Paratagging causes an extra blank line when display math is followed by a paragraph break.

```latex
\DocumentMetadata{}
\RequirePackage{tagpdf}
\tagpdfsetup{activate, paratagging}

\documentclass{article}

\begin{document}
Eaque laboriosam necessitatibus itaque suscipit modi.
\[a+b=c.\]

Non reprehenderit tempora corporis perspiciatis cum quod aut.
\end{document}
```

Result:
![PDF with an extra blank line](https://github.com/u-fischer/tagpdf/assets/24620923/4fdebbee-155f-4a5c-9441-81c88b1101cd)

Happens with pdflatex(-dev). Does not happen with lualatex(-dev), unless `paratagging-show` is used.

[tagpdf-test.log](https://github.com/u-fischer/tagpdf/files/12567953/tagpdf-test.log)

**Comment by u-fischer** [comment]
yes there is a literal which affects spacing.  You need proper math tagging to resolve that, so you should load the math-code from latex-lab (but that has another problem  I discovered through your example: https://github.com/latex3/tagging-project/issues/11). 

Generally I recommend to load the tagging code through the testphase keys and not as package:

~~~~
\DocumentMetadata{testphase={phase-II,math}}
~~~~
